FROM --platform=linux/amd64 python:3.11-slim

WORKDIR /app

RUN pip install tweepy praw requests schedule python-dotenv

COPY phase1_cloud_ready.py /app/
COPY .env /app/

CMD ["python3", "phase1_cloud_ready.py"]
